# Generated by Django 5.0.1 on 2024-04-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
