# Generated by Django 5.0.1 on 2024-04-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=150, verbose_name='Height')),
                ('weight', models.FloatField(default=50, verbose_name='Weight')),
                ('bmi_value', models.FloatField(blank=True, null=True, verbose_name='BMI Value')),
                ('bmi', models.CharField(blank=True, choices=[('SEVERE THINNESS', 'SEVERE THINNESS'), ('MODERATE THINNESS', 'MODERATE THINNESS'), ('MILD THINNESS', 'MILD THINNESS'), ('NORMAL', 'NORMAL'), ('OVER WEIGHT', 'OVER WEIGHT'), ('OBESE CLASS I', 'OBESE CLASS I'), ('OBESE CLASS II', 'OBESE CLASS II'), ('OBESE CLASS III', 'OBESE CLASS III')], max_length=50, null=True, verbose_name='BMI')),
                ('physical_activity', models.PositiveIntegerField(default=1, verbose_name='Physical Activity')),
                ('screen_time', models.PositiveIntegerField(default=1, verbose_name='Screen Time')),
                ('stress_level', models.PositiveIntegerField(default=5, verbose_name='Stress Level')),
                ('heart_rate', models.PositiveIntegerField(default=80, verbose_name='Heart Rate')),
                ('systolic_pressure', models.PositiveIntegerField(default=105, verbose_name='Systolic Pressure')),
                ('systolic_pressure_bp', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('LOW', 'LOW'), ('HIGH BLOOD PRESSURE', 'HIGH BLOOD PRESSURE'), ('VERY HIGH BLOOD PRESSURE', 'VERY HIGH BLOOD PRESSURE')], max_length=50, null=True, verbose_name='Systolic Pressure BP')),
                ('diastolic_pressure', models.PositiveIntegerField(default=70, verbose_name='Diastolic Pressure')),
                ('diastolic_pressure_bp', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('LOW', 'LOW'), ('HIGH BLOOD PRESSURE', 'HIGH BLOOD PRESSURE'), ('VERY HIGH BLOOD PRESSURE', 'VERY HIGH BLOOD PRESSURE')], max_length=50, null=True, verbose_name='Diastolic Pressure BP')),
                ('sleep_duration', models.PositiveIntegerField(default=300, verbose_name='Sleep Duration')),
                ('quality_of_sleep', models.PositiveIntegerField(default=5, null=True, verbose_name='Quality of Sleep')),
                ('sleep_disorder', models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('CIRCADIAN RHYTHM SLEEP DISORDERS', 'CIRCADIAN RHYTHM SLEEP DISORDERS'), ('HYPERSOMNIA DISORDERS', 'HYPERSOMNIA DISORDERS'), ('INSOMNIA', 'INSOMNIA'), ('PARASOMNIAS ', 'PARASOMNIAS '), ('SLEEP APNEA', 'SLEEP APNEA')], max_length=50, null=True, verbose_name='Sleep Disorder')),
                ('healthprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to='healthprofile.healthprofile')),
            ],
        ),
    ]
