# Generated by Django 5.0.1 on 2024-02-06 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthrecord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthprofile',
            name='occupations',
        ),
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='occupations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='healthrecord.occupation'),
        ),
    ]
