# Generated by Django 5.0.1 on 2024-02-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthprofile',
            old_name='occupations',
            new_name='occupation',
        ),
    ]
