# Generated by Django 5.0.1 on 2024-02-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofileapp', '0002_rename_occupations_healthprofile_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0, help_text='Enter height in meters', verbose_name='Height')),
                ('weight', models.FloatField(default=0, help_text='Enter weight in kilograms', verbose_name='Weight')),
                ('physical_activity', models.PositiveIntegerField(default=0, help_text='Enter level of physical activity in minutes', verbose_name='Physical Activity')),
                ('daily_steps', models.PositiveIntegerField(default=0, help_text='Enter daily steps count', verbose_name='Daily Steps')),
                ('blood_pressure', models.CharField(default='120/80 mmHg', help_text='Enter blood pressure measurement', max_length=20, verbose_name='Blood Pressure')),
                ('heart_rate', models.PositiveIntegerField(default=0, help_text='Enter heart rate', verbose_name='Heart Rate')),
                ('sleep_duration', models.FloatField(default=0, help_text='Enter sleep duration in hours', verbose_name='Sleep Duration')),
                ('quality_of_sleep', models.IntegerField(blank=True, help_text='Enter quality of sleep on a scale of 1 to 10', null=True, verbose_name='Quality of Sleep')),
                ('stress_level', models.IntegerField(blank=True, help_text='Enter stress level on a scale of 1 to 10', null=True, verbose_name='Stress Level')),
                ('bmi', models.CharField(blank=True, choices=[('Severe Thinness', 'Severe Thinness'), ('Moderate Thinness', 'Moderate Thinness'), ('Mild Thinness', 'Mild Thinness'), ('Normal', 'Normal'), ('Overweight', 'Overweight'), ('Obese Class I', 'Obese Class I'), ('Obese Class II', 'Obese Class II'), ('Obese Class III', 'Obese Class III')], max_length=50, null=True, verbose_name='BMI')),
                ('sleep_disorder', models.CharField(blank=True, choices=[('No', 'No'), ('Insomnia', 'Insomnia'), ('Sleep Apnea', 'Sleep Apnea'), ('Narcolepsy', 'Narcolepsy'), ('Restless Legs Syndrome (RLS)', 'Restless Legs Syndrome (RLS)'), ('Periodic Limb Movement Disorder (PLMD)', 'Periodic Limb Movement Disorder (PLMD)'), ('Parasomnias', 'Parasomnias'), ('Circadian Rhythm Sleep Disorders', 'Circadian Rhythm Sleep Disorders'), ('Hypersomnia', 'Hypersomnia'), ('Sleep-related movement disorders', 'Sleep-related movement disorders'), ('Sleep-related breathing disorders', 'Sleep-related breathing disorders')], max_length=50, null=True, verbose_name='Sleep Disorder')),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to='healthprofileapp.healthprofile')),
            ],
        ),
    ]
