# Generated by Django 5.0.1 on 2024-02-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofileapp', '0003_sleeprecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SleepRecord',
            new_name='HealthRecords',
        ),
    ]
