# Generated by Django 5.0.1 on 2024-02-18 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofileapp', '0004_rename_sleeprecord_healthrecords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthrecords',
            old_name='health_profile',
            new_name='healthprofile',
        ),
    ]
