# Generated by Django 5.0.1 on 2024-02-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofileapp', '0005_rename_health_profile_healthrecords_healthprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthRecords',
            new_name='HealthRecord',
        ),
    ]
