# Generated by Django 5.0.1 on 2024-03-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthprofileapp', '0006_rename_healthrecords_healthrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='daily_steps',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='bmi_value',
            field=models.FloatField(blank=True, null=True, verbose_name='BMI Value'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='diastolic_pressure',
            field=models.PositiveIntegerField(default=70, verbose_name='Diastolic Pressure'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='diastolic_pressure_bp',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('LOW', 'LOW'), ('HIGH BLOOD PRESSURE', 'HIGH BLOOD PRESSURE'), ('VERY HIGH BLOOD PRESSURE', 'VERY HIGH BLOOD PRESSURE')], max_length=50, null=True, verbose_name='Diastolic Pressure BP'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='screen_time',
            field=models.PositiveIntegerField(default=1, verbose_name='Screen Time'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='systolic_pressure',
            field=models.PositiveIntegerField(default=105, verbose_name='Systolic Pressure'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='systolic_pressure_bp',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('LOW', 'LOW'), ('HIGH BLOOD PRESSURE', 'HIGH BLOOD PRESSURE'), ('VERY HIGH BLOOD PRESSURE', 'VERY HIGH BLOOD PRESSURE')], max_length=50, null=True, verbose_name='Systolic Pressure BP'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=25),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='bmi',
            field=models.CharField(blank=True, choices=[('SEVERE THINNESS', 'SEVERE THINNESS'), ('MODERATE THINNESS', 'MODERATE THINNESS'), ('MILD THINNESS', 'MILD THINNESS'), ('NORMAL', 'NORMAL'), ('OVER WEIGHT', 'OVER WEIGHT'), ('OBESE CLASS I', 'OBESE CLASS I'), ('OBESE CLASS II', 'OBESE CLASS II'), ('OBESE CLASS III', 'OBESE CLASS III')], max_length=50, null=True, verbose_name='BMI'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='heart_rate',
            field=models.PositiveIntegerField(default=80, verbose_name='Heart Rate'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='height',
            field=models.FloatField(default=150, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='physical_activity',
            field=models.PositiveIntegerField(default=1, verbose_name='Physical Activity'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='quality_of_sleep',
            field=models.PositiveIntegerField(default=5, null=True, verbose_name='Quality of Sleep'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='sleep_disorder',
            field=models.CharField(blank=True, choices=[('NORMAL', 'NORMAL'), ('CIRCADIAN RHYTHM SLEEP DISORDERS', 'CIRCADIAN RHYTHM SLEEP DISORDERS'), ('HYPERSOMNIA DISORDERS', 'HYPERSOMNIA DISORDERS'), ('INSOMNIA', 'INSOMNIA'), ('PARASOMNIAS ', 'PARASOMNIAS '), ('SLEEP APNEA', 'SLEEP APNEA')], max_length=50, null=True, verbose_name='Sleep Disorder'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='sleep_duration',
            field=models.PositiveIntegerField(default=300, verbose_name='Sleep Duration'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='stress_level',
            field=models.PositiveIntegerField(default=5, verbose_name='Stress Level'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='weight',
            field=models.FloatField(default=50, verbose_name='Weight'),
        ),
    ]
